-- drop objects
drop table d07_error_lookup cascade constraints;

-- create tables
create table d07_error_lookup (
    id                             number generated by default on null as identity 
                                   constraint d07_error_lookup_id_pk primary key,
    constraint_name                varchar2(30 char) not null,
    message                        varchar2(4000 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;


-- triggers
create or replace trigger d07_error_lookup_biu
    before insert or update 
    on d07_error_lookup
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d07_error_lookup_biu;
/

-- load data
 
-- Generated by Quick SQL Martedì Agosto 29, 2023  09:13:44
 
/*
error_lookup 
  constraint_name vc30 /nn
  message vc4000 /nn



# settings = { prefix: "D07", semantics: "CHAR", auditCols: true, drop: true, language: "EN", APEX: true }
*/
